# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='session',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
